import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, FileText, Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { EmptyState, LoadingCards, PageHeader, PillDanger, PillNeutral, PillWarn } from "@/components/bits";
import { supabase } from "@/integrations/supabase/client";
import { useAccount } from "@/lib/account";
import { fmtDate, todayISO } from "@/lib/data";
import { useLang } from "@/lib/i18n";

export const Route = createFileRoute("/dokumenty")({
  staticData: { sitemap: false },
  validateSearch: (search: Record<string, unknown>) => ({ task: typeof search["task"] === "string" ? search["task"] : "" }),
  head: () => ({ meta: [
    { title: "Document Vault — My Chata" }, { name: "description", content: "Private cottage documents, warranties, and expiry reminders." },
    { property: "og:title", content: "Document Vault — My Chata" }, { property: "og:description", content: "Private cottage documents, warranties, and expiry reminders." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
  ] }), component: DocumentsPage,
});

const categories = ["INSURANCE", "OWNERSHIP", "UTILITIES", "SERVICE_RECORDS", "WARRANTIES", "OTHER"];

function DocumentsPage() {
  const { task: linkedTaskId } = Route.useSearch();
  const { property, currentMember } = useAccount(); const { t } = useLang(); const queryClient = useQueryClient();
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("ALL"); const [adding, setAdding] = useState(!!linkedTaskId);
  const [form, setForm] = useState({ title: "", category: linkedTaskId ? "WARRANTIES" : "OTHER", notes: "", issueDate: "", expiryDate: "", visibility: "ALL_MEMBERS" });
  const [file, setFile] = useState<File | null>(null); const isAdmin = currentMember?.role === "ADMIN" || currentMember?.role === "OWNER";
  const { data: documents, isLoading } = useQuery({ queryKey: ["documents", property?.id], enabled: !!property, queryFn: async () => { const { data, error } = await supabase.from("documents").select("*").eq("property_id", property?.id ?? "").order("created_at", { ascending: false }); if (error) throw error; return data; } });
  const visible = useMemo(() => (documents ?? []).filter((document) => (category === "ALL" || document.category === category) && `${document.title} ${document.notes ?? ""}`.toLowerCase().includes(query.toLowerCase())), [documents, category, query]);
  const save = useMutation({ mutationFn: async () => {
    if (!property) return; let fileUrl: string | null = null;
    if (file) { const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, "-"); const path = `${property.id}/${crypto.randomUUID()}-${safeName}`; const { error } = await supabase.storage.from("my-chata-files").upload(path, file); if (error) throw error; fileUrl = path; }
    const { error } = await supabase.from("documents").insert({ property_id: property.id, linked_task_id: linkedTaskId || null, title: form.title, category: form.category, notes: form.notes || null, issue_date: form.issueDate || null, expiry_date: form.expiryDate || null, visibility: form.visibility, file_url: fileUrl }); if (error) throw error;
  }, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["documents", property?.id] }); setAdding(false); setFile(null); setForm({ title: "", category: "OTHER", notes: "", issueDate: "", expiryDate: "", visibility: "ALL_MEMBERS" }); toast.success(t("Dokument uložen.", "Document saved.")); }, onError: () => toast.error(t("Dokument se nepodařilo uložit. Přihlaste se a zkuste to znovu.", "Could not save the document. Sign in and try again.")) });
  const openFile = async (path: string | null) => { if (!path) return; const { data, error } = await supabase.storage.from("my-chata-files").createSignedUrl(path, 60); if (error) { toast.error(t("Soubor nelze otevřít.", "Could not open the file.")); return; } window.open(data.signedUrl, "_blank", "noopener,noreferrer"); };
  const remove = async (id: string, path: string | null) => { if (path) await supabase.storage.from("my-chata-files").remove([path]); const { error } = await supabase.from("documents").delete().eq("id", id); if (error) { toast.error(t("Dokument nelze smazat.", "Could not delete the document.")); return; } queryClient.invalidateQueries({ queryKey: ["documents", property?.id] }); };
  const daysUntil = (date: string) => Math.ceil((new Date(`${date}T00:00:00`).getTime() - new Date(`${todayISO()}T00:00:00`).getTime()) / 86400000);
  return <AppShell><PageHeader title={t("Dokumenty", "Document Vault")} subtitle={t("Smlouvy, záruky a servisní záznamy", "Contracts, warranties, and service records")} back="/vice" action={isAdmin ? <button onClick={() => setAdding(true)} className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground" aria-label={t("Přidat dokument", "Add document")}><Plus className="size-5" /></button> : null} />
    <div className="mb-4 flex gap-2"><label className="field flex items-center gap-2"><Search className="size-5 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent outline-none" placeholder={t("Hledat", "Search")} /></label><select value={category} onChange={(e) => setCategory(e.target.value)} className="field w-36"><option value="ALL">{t("Vše", "All")}</option>{categories.map((value) => <option key={value}>{value}</option>)}</select></div>
    {isLoading ? <LoadingCards /> : !visible.length ? <EmptyState icon={FileText} title={t("Žádné dokumenty.", "No documents.")} /> : <div className="space-y-3">{visible.map((document) => { const days = document.expiry_date ? daysUntil(document.expiry_date) : null; return <article key={document.id} className="card p-4"><div className="flex items-start gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-secondary"><FileText className="size-5" /></div><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{document.title}</h2><p className="text-[13px] text-muted-foreground">{document.category}</p></div>{days !== null && days < 0 ? <PillDanger>{t("Po platnosti", "Expired")}</PillDanger> : days !== null && days <= 30 ? <PillWarn>{days} {t("dní", "days")}</PillWarn> : <PillNeutral>{document.visibility === "ADMINS_ONLY" ? t("Správci", "Admins") : t("Členové", "Members")}</PillNeutral>}</div>{document.notes && <p className="mt-2 text-[14px]">{document.notes}</p>}{document.expiry_date && <p className="mt-2 text-[13px] font-semibold text-muted-foreground">{t("Platnost do", "Expires")} {fmtDate(document.expiry_date)}</p>}<div className="mt-3 flex gap-2">{document.file_url && <button onClick={() => openFile(document.file_url)} className="btn-secondary flex-1"><Download className="size-4" />{t("Otevřít", "Open")}</button>}{isAdmin && <button onClick={() => remove(document.id, document.file_url)} className="grid size-11 place-items-center rounded-xl bg-primary-soft text-primary" aria-label={t("Smazat", "Delete")}><Trash2 className="size-5" /></button>}</div></article>; })}</div>}
    {adding && <div className="fixed inset-0 z-50 grid place-items-end bg-foreground/35 p-4 sm:place-items-center"><form onSubmit={(e) => { e.preventDefault(); save.mutate(); }} className="card max-h-[90vh] w-full max-w-[400px] space-y-3 overflow-auto p-4"><h2 className="text-xl font-bold">{linkedTaskId ? t("Záruka k dokončenému úkolu", "Warranty for completed task") : t("Nový dokument", "New document")}</h2><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="field" placeholder={t("Název", "Title")} /><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="field">{categories.map((value) => <option key={value}>{value}</option>)}</select><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="field" placeholder={t("Poznámky", "Notes")} /><label className="block text-[13px] font-bold">{t("Datum vystavení", "Issue date")}<input type="date" value={form.issueDate} onChange={(e) => setForm({ ...form, issueDate: e.target.value })} className="field mt-1" /></label><label className="block text-[13px] font-bold">{t("Platnost do", "Expiry date")}<input type="date" value={form.expiryDate} onChange={(e) => setForm({ ...form, expiryDate: e.target.value })} className="field mt-1" /></label><select value={form.visibility} onChange={(e) => setForm({ ...form, visibility: e.target.value })} className="field"><option value="ALL_MEMBERS">{t("Všichni členové", "All members")}</option><option value="ADMINS_ONLY">{t("Jen správci", "Admins only")}</option></select><input type="file" accept="application/pdf,image/jpeg,image/png" onChange={(e) => setFile(e.target.files?.[0] ?? null)} className="field" /><div className="flex gap-2"><button className="btn-primary flex-1">{t("Uložit", "Save")}</button><button type="button" onClick={() => setAdding(false)} className="btn-secondary">{t("Zrušit", "Cancel")}</button></div></form></div>}
  </AppShell>;
}