/**
 * Writes docs/generated/schema.md and docs/generated/routes.md from the code itself,
 * so agents read ~300 lines instead of types.ts plus every migration.
 *   bun run docs:gen          regenerate
 *   bun run docs:check        fail if the committed files are out of date (CI)
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { freshDb } from "../supabase/tests/harness";

const ROOT = join(import.meta.dirname, "..");
const check = process.argv.includes("--check");

async function schemaDoc(): Promise<string> {
  const db = await freshDb();
  const q = async <T>(sql: string) => (await db.query<T>(sql)).rows;
  const cols = await q<{
    t: string;
    c: string;
    type: string;
    nullable: string;
    def: string | null;
  }>(`
    select table_name as t, column_name as c, data_type as type, is_nullable as nullable, column_default as def
      from information_schema.columns where table_schema = 'public' order by table_name, ordinal_position`);
  const pols = await q<{ t: string; name: string; cmd: string; roles: string[] | string }>(`
    select tablename as t, policyname as name, cmd, roles from pg_policies
     where schemaname = 'public' order by tablename, policyname`);
  const fns = await q<{
    name: string;
    args: string;
    definer: boolean;
    anon: boolean;
    auth: boolean;
  }>(`
    select p.proname as name, pg_get_function_identity_arguments(p.oid) as args, p.prosecdef as definer,
           has_function_privilege('anon', p.oid, 'execute') as anon,
           has_function_privilege('authenticated', p.oid, 'execute') as auth
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prolang in (select oid from pg_language where lanname in ('sql', 'plpgsql'))
       and p.proname not like 'f\\_%'
     order by 1, 2`);
  const tables = [...new Set(cols.map((c) => c.t))];
  const out: string[] = [
    "# Database schema (generated)",
    "",
    "Generated by `bun run docs:gen` from all migrations. Do not edit by hand.",
    "",
    "## Functions",
    "",
    "| Function | Args | Definer | anon | signed-in |",
    "| --- | --- | --- | --- | --- |",
    ...fns.map(
      (f) =>
        `| ${f.name} | ${f.args || "–"} | ${f.definer ? "yes" : ""} | ${f.anon ? "yes" : ""} | ${f.auth ? "yes" : ""} |`,
    ),
    "",
    "## Tables",
    "",
  ];
  for (const t of tables) {
    out.push(`### ${t}`, "");
    out.push(
      cols
        .filter((c) => c.t === t)
        .map((c) => `\`${c.c}\` ${c.type}${c.nullable === "NO" ? "" : "?"}`)
        .join(" · "),
      "",
    );
    const p = pols.filter((x) => x.t === t);
    if (p.length) {
      out.push("Policies: " + p.map((x) => `${x.name} (${x.cmd})`).join("; "), "");
    }
  }
  return out.join("\n");
}

function routesDoc(): string {
  const files = readdirSync(join(ROOT, "src", "routes"))
    .filter((f) => /\.(tsx|ts)$/.test(f) && !f.startsWith("__"))
    .sort();
  const rows = files.map((f) => {
    const src = readFileSync(join(ROOT, "src", "routes", f), "utf8");
    const path = /createFileRoute\("([^"]+)"\)/.exec(src)?.[1] ?? "(server route)";
    const isPublic =
      /^\/(verejne|host|pozvanka|auth|reset-password|sitemap|$)/.test(path) || path === "/";
    return `| \`${path}\` | ${f} | ${isPublic ? "public" : "signed-in"} |`;
  });
  return [
    "# Routes (generated)",
    "",
    "Generated by `bun run docs:gen` from `src/routes`. Do not edit by hand.",
    "",
    "| URL | File | Access |",
    "| --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

const targets: [string, string][] = [
  [join(ROOT, "docs", "generated", "schema.md"), await schemaDoc()],
  [join(ROOT, "docs", "generated", "routes.md"), routesDoc()],
];
let stale = 0;
for (const [file, content] of targets) {
  let current = "";
  try {
    current = readFileSync(file, "utf8");
  } catch {
    /* missing */
  }
  if (current === content) continue;
  if (check) {
    console.error(`Out of date: ${file}. Run: bun run docs:gen`);
    stale++;
  } else {
    writeFileSync(file, content);
    console.log(`Wrote ${file}`);
  }
}
process.exit(stale ? 1 : 0);
