/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DokumentyRouteImport } from './routes/dokumenty'
import { Route as DomuRouteImport } from './routes/domu'
import { Route as ExportRouteImport } from './routes/export'
import { Route as KalendarRouteImport } from './routes/kalendar'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PredaniRouteImport } from './routes/predani'
import { Route as SchvalovaniRouteImport } from './routes/schvalovani'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UkolyRouteImport } from './routes/ukoly'
import { Route as ViceRouteImport } from './routes/vice'
import { Route as VydajeRouteImport } from './routes/vydaje'
import { Route as ZadostiRouteImport } from './routes/zadosti'
import { Route as RezervaceIdRouteImport } from './routes/rezervace.$id'
import { Route as RezervaceNovaRouteImport } from './routes/rezervace.nova'
import { Route as UkolyIdRouteImport } from './routes/ukoly.$id'
import { Route as VerejneZadostRouteImport } from './routes/verejne.zadost'
import { Route as VydajeVyrovnaniRouteImport } from './routes/vydaje.vyrovnani'
import { Route as VerejneKalendarPropertyIdRouteImport } from './routes/verejne.kalendar.$propertyId'
import { Route as VerejneManualPropertyIdRouteImport } from './routes/verejne.manual.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentyRoute = DokumentyRouteImport.update({
  id: '/dokumenty',
  path: '/dokumenty',
  getParentRoute: () => rootRouteImport,
} as any)
const DomuRoute = DomuRouteImport.update({
  id: '/domu',
  path: '/domu',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const KalendarRoute = KalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PredaniRoute = PredaniRouteImport.update({
  id: '/predani',
  path: '/predani',
  getParentRoute: () => rootRouteImport,
} as any)
const SchvalovaniRoute = SchvalovaniRouteImport.update({
  id: '/schvalovani',
  path: '/schvalovani',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UkolyRoute = UkolyRouteImport.update({
  id: '/ukoly',
  path: '/ukoly',
  getParentRoute: () => rootRouteImport,
} as any)
const ViceRoute = ViceRouteImport.update({
  id: '/vice',
  path: '/vice',
  getParentRoute: () => rootRouteImport,
} as any)
const VydajeRoute = VydajeRouteImport.update({
  id: '/vydaje',
  path: '/vydaje',
  getParentRoute: () => rootRouteImport,
} as any)
const ZadostiRoute = ZadostiRouteImport.update({
  id: '/zadosti',
  path: '/zadosti',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervaceIdRoute = RezervaceIdRouteImport.update({
  id: '/rezervace/$id',
  path: '/rezervace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervaceNovaRoute = RezervaceNovaRouteImport.update({
  id: '/rezervace/nova',
  path: '/rezervace/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const UkolyIdRoute = UkolyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UkolyRoute,
} as any)
const VerejneZadostRoute = VerejneZadostRouteImport.update({
  id: '/verejne/zadost',
  path: '/verejne/zadost',
  getParentRoute: () => rootRouteImport,
} as any)
const VydajeVyrovnaniRoute = VydajeVyrovnaniRouteImport.update({
  id: '/vyrovnani',
  path: '/vyrovnani',
  getParentRoute: () => VydajeRoute,
} as any)
const VerejneKalendarPropertyIdRoute =
  VerejneKalendarPropertyIdRouteImport.update({
    id: '/verejne/kalendar/$propertyId',
    path: '/verejne/kalendar/$propertyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerejneManualPropertyIdRoute = VerejneManualPropertyIdRouteImport.update({
  id: '/verejne/manual/$propertyId',
  path: '/verejne/manual/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dokumenty': typeof DokumentyRoute
  '/domu': typeof DomuRoute
  '/export': typeof ExportRoute
  '/kalendar': typeof KalendarRoute
  '/manual': typeof ManualRoute
  '/onboarding': typeof OnboardingRoute
  '/predani': typeof PredaniRoute
  '/schvalovani': typeof SchvalovaniRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ukoly': typeof UkolyRouteWithChildren
  '/vice': typeof ViceRoute
  '/vydaje': typeof VydajeRouteWithChildren
  '/zadosti': typeof ZadostiRoute
  '/rezervace/$id': typeof RezervaceIdRoute
  '/rezervace/nova': typeof RezervaceNovaRoute
  '/ukoly/$id': typeof UkolyIdRoute
  '/verejne/zadost': typeof VerejneZadostRoute
  '/vydaje/vyrovnani': typeof VydajeVyrovnaniRoute
  '/verejne/kalendar/$propertyId': typeof VerejneKalendarPropertyIdRoute
  '/verejne/manual/$propertyId': typeof VerejneManualPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dokumenty': typeof DokumentyRoute
  '/domu': typeof DomuRoute
  '/export': typeof ExportRoute
  '/kalendar': typeof KalendarRoute
  '/manual': typeof ManualRoute
  '/onboarding': typeof OnboardingRoute
  '/predani': typeof PredaniRoute
  '/schvalovani': typeof SchvalovaniRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ukoly': typeof UkolyRouteWithChildren
  '/vice': typeof ViceRoute
  '/vydaje': typeof VydajeRouteWithChildren
  '/zadosti': typeof ZadostiRoute
  '/rezervace/$id': typeof RezervaceIdRoute
  '/rezervace/nova': typeof RezervaceNovaRoute
  '/ukoly/$id': typeof UkolyIdRoute
  '/verejne/zadost': typeof VerejneZadostRoute
  '/vydaje/vyrovnani': typeof VydajeVyrovnaniRoute
  '/verejne/kalendar/$propertyId': typeof VerejneKalendarPropertyIdRoute
  '/verejne/manual/$propertyId': typeof VerejneManualPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dokumenty': typeof DokumentyRoute
  '/domu': typeof DomuRoute
  '/export': typeof ExportRoute
  '/kalendar': typeof KalendarRoute
  '/manual': typeof ManualRoute
  '/onboarding': typeof OnboardingRoute
  '/predani': typeof PredaniRoute
  '/schvalovani': typeof SchvalovaniRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ukoly': typeof UkolyRouteWithChildren
  '/vice': typeof ViceRoute
  '/vydaje': typeof VydajeRouteWithChildren
  '/zadosti': typeof ZadostiRoute
  '/rezervace/$id': typeof RezervaceIdRoute
  '/rezervace/nova': typeof RezervaceNovaRoute
  '/ukoly/$id': typeof UkolyIdRoute
  '/verejne/zadost': typeof VerejneZadostRoute
  '/vydaje/vyrovnani': typeof VydajeVyrovnaniRoute
  '/verejne/kalendar/$propertyId': typeof VerejneKalendarPropertyIdRoute
  '/verejne/manual/$propertyId': typeof VerejneManualPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dokumenty'
    | '/domu'
    | '/export'
    | '/kalendar'
    | '/manual'
    | '/onboarding'
    | '/predani'
    | '/schvalovani'
    | '/sitemap.xml'
    | '/ukoly'
    | '/vice'
    | '/vydaje'
    | '/zadosti'
    | '/rezervace/$id'
    | '/rezervace/nova'
    | '/ukoly/$id'
    | '/verejne/zadost'
    | '/vydaje/vyrovnani'
    | '/verejne/kalendar/$propertyId'
    | '/verejne/manual/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dokumenty'
    | '/domu'
    | '/export'
    | '/kalendar'
    | '/manual'
    | '/onboarding'
    | '/predani'
    | '/schvalovani'
    | '/sitemap.xml'
    | '/ukoly'
    | '/vice'
    | '/vydaje'
    | '/zadosti'
    | '/rezervace/$id'
    | '/rezervace/nova'
    | '/ukoly/$id'
    | '/verejne/zadost'
    | '/vydaje/vyrovnani'
    | '/verejne/kalendar/$propertyId'
    | '/verejne/manual/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dokumenty'
    | '/domu'
    | '/export'
    | '/kalendar'
    | '/manual'
    | '/onboarding'
    | '/predani'
    | '/schvalovani'
    | '/sitemap.xml'
    | '/ukoly'
    | '/vice'
    | '/vydaje'
    | '/zadosti'
    | '/rezervace/$id'
    | '/rezervace/nova'
    | '/ukoly/$id'
    | '/verejne/zadost'
    | '/vydaje/vyrovnani'
    | '/verejne/kalendar/$propertyId'
    | '/verejne/manual/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DokumentyRoute: typeof DokumentyRoute
  DomuRoute: typeof DomuRoute
  ExportRoute: typeof ExportRoute
  KalendarRoute: typeof KalendarRoute
  ManualRoute: typeof ManualRoute
  OnboardingRoute: typeof OnboardingRoute
  PredaniRoute: typeof PredaniRoute
  SchvalovaniRoute: typeof SchvalovaniRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UkolyRoute: typeof UkolyRouteWithChildren
  ViceRoute: typeof ViceRoute
  VydajeRoute: typeof VydajeRouteWithChildren
  ZadostiRoute: typeof ZadostiRoute
  RezervaceIdRoute: typeof RezervaceIdRoute
  RezervaceNovaRoute: typeof RezervaceNovaRoute
  VerejneZadostRoute: typeof VerejneZadostRoute
  VerejneKalendarPropertyIdRoute: typeof VerejneKalendarPropertyIdRoute
  VerejneManualPropertyIdRoute: typeof VerejneManualPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenty': {
      id: '/dokumenty'
      path: '/dokumenty'
      fullPath: '/dokumenty'
      preLoaderRoute: typeof DokumentyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domu': {
      id: '/domu'
      path: '/domu'
      fullPath: '/domu'
      preLoaderRoute: typeof DomuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalendar': {
      id: '/kalendar'
      path: '/kalendar'
      fullPath: '/kalendar'
      preLoaderRoute: typeof KalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predani': {
      id: '/predani'
      path: '/predani'
      fullPath: '/predani'
      preLoaderRoute: typeof PredaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schvalovani': {
      id: '/schvalovani'
      path: '/schvalovani'
      fullPath: '/schvalovani'
      preLoaderRoute: typeof SchvalovaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukoly': {
      id: '/ukoly'
      path: '/ukoly'
      fullPath: '/ukoly'
      preLoaderRoute: typeof UkolyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vice': {
      id: '/vice'
      path: '/vice'
      fullPath: '/vice'
      preLoaderRoute: typeof ViceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vydaje': {
      id: '/vydaje'
      path: '/vydaje'
      fullPath: '/vydaje'
      preLoaderRoute: typeof VydajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zadosti': {
      id: '/zadosti'
      path: '/zadosti'
      fullPath: '/zadosti'
      preLoaderRoute: typeof ZadostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervace/$id': {
      id: '/rezervace/$id'
      path: '/rezervace/$id'
      fullPath: '/rezervace/$id'
      preLoaderRoute: typeof RezervaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervace/nova': {
      id: '/rezervace/nova'
      path: '/rezervace/nova'
      fullPath: '/rezervace/nova'
      preLoaderRoute: typeof RezervaceNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukoly/$id': {
      id: '/ukoly/$id'
      path: '/$id'
      fullPath: '/ukoly/$id'
      preLoaderRoute: typeof UkolyIdRouteImport
      parentRoute: typeof UkolyRoute
    }
    '/verejne/zadost': {
      id: '/verejne/zadost'
      path: '/verejne/zadost'
      fullPath: '/verejne/zadost'
      preLoaderRoute: typeof VerejneZadostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vydaje/vyrovnani': {
      id: '/vydaje/vyrovnani'
      path: '/vyrovnani'
      fullPath: '/vydaje/vyrovnani'
      preLoaderRoute: typeof VydajeVyrovnaniRouteImport
      parentRoute: typeof VydajeRoute
    }
    '/verejne/kalendar/$propertyId': {
      id: '/verejne/kalendar/$propertyId'
      path: '/verejne/kalendar/$propertyId'
      fullPath: '/verejne/kalendar/$propertyId'
      preLoaderRoute: typeof VerejneKalendarPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verejne/manual/$propertyId': {
      id: '/verejne/manual/$propertyId'
      path: '/verejne/manual/$propertyId'
      fullPath: '/verejne/manual/$propertyId'
      preLoaderRoute: typeof VerejneManualPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UkolyRouteChildren {
  UkolyIdRoute: typeof UkolyIdRoute
}

const UkolyRouteChildren: UkolyRouteChildren = {
  UkolyIdRoute: UkolyIdRoute,
}

const UkolyRouteWithChildren = UkolyRoute._addFileChildren(UkolyRouteChildren)

interface VydajeRouteChildren {
  VydajeVyrovnaniRoute: typeof VydajeVyrovnaniRoute
}

const VydajeRouteChildren: VydajeRouteChildren = {
  VydajeVyrovnaniRoute: VydajeVyrovnaniRoute,
}

const VydajeRouteWithChildren =
  VydajeRoute._addFileChildren(VydajeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DokumentyRoute: DokumentyRoute,
  DomuRoute: DomuRoute,
  ExportRoute: ExportRoute,
  KalendarRoute: KalendarRoute,
  ManualRoute: ManualRoute,
  OnboardingRoute: OnboardingRoute,
  PredaniRoute: PredaniRoute,
  SchvalovaniRoute: SchvalovaniRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UkolyRoute: UkolyRouteWithChildren,
  ViceRoute: ViceRoute,
  VydajeRoute: VydajeRouteWithChildren,
  ZadostiRoute: ZadostiRoute,
  RezervaceIdRoute: RezervaceIdRoute,
  RezervaceNovaRoute: RezervaceNovaRoute,
  VerejneZadostRoute: VerejneZadostRoute,
  VerejneKalendarPropertyIdRoute: VerejneKalendarPropertyIdRoute,
  VerejneManualPropertyIdRoute: VerejneManualPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
